name: second_try
description: "A new Flutter project."

publish_to:


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.0  # Для запроса разрешений
  shared_preferences: ^2.3.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2        # Для выбора фото
  image_cropper: ^7.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

